import type { Candidate } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    phoneNumber: '+4915208526138',
    email: 'marcel.weber@example.com',
    address: 'Augsburger Str. 14, 80337 München',
    city: 'München',
    firstName: 'Marcel',
    lastName: 'Weber',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['No answer'],
    analysisOutcome: 'wrong_person',
    dateOfBirth: '1990-02-18',
    germanLevel: 'B2',
    training: 'Betriebselektriker',
    salary: null,
    earliestStart: null,
    driversLicense: false,
    licenseClasses: null,
    lastJobs: [],
    jobChangeMotivation: null,
    specialSkills: null,
    additionalPreferences: null,
    status: 'failed',
    employmentStatus: 'looking-for-job',
    pipelineStatus: 'call',
    needForAction: 'high',
    recruiter: 'Tanina',
    touchpoints: 1,
    duration: null,
    lastContactAt: '2026-04-10',
    aiAdoption: 'low',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-10T09:23:00Z',
  },
  {
    id: '2',
    phoneNumber: '+491716437340',
    email: 'andi.kufner@example.com',
    address: 'Marienplatz 8, 80331 München',
    city: 'München',
    firstName: 'Andi',
    lastName: 'Kufner',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: [],
    analysisOutcome: 'interview_completed_full',
    dateOfBirth: '1988-03-14',
    germanLevel: 'B2',
    training: 'Elektrotechnik',
    salary: '2800',
    earliestStart: '2026-05-01',
    driversLicense: true,
    licenseClasses: 'B',
    lastJobs: ['Techniker bei Siemens', 'Wartungsservice GmbH'],
    jobChangeMotivation: 'Bessere Karrieremöglichkeiten und mehr Gehalt.',
    specialSkills: 'Kaffeemaschinen-Reparatur, Elektrik',
    additionalPreferences: 'Homeoffice teilweise möglich',
    status: 'done',
    employmentStatus: 'applying',
    pipelineStatus: 'matched',
    needForAction: 'low',
    recruiter: 'Berti',
    touchpoints: 3,
    duration: '4:23',
    lastContactAt: '2026-04-14',
    aiAdoption: 'high',
    terminationReason: 'Call ended by remote party',
    transcriptSummary:
      'Der KI-Agent Sophia hat den Kandidaten Andi Kufner erfolgreich interviewt. Er hat relevante Erfahrung in der Elektrotechnik und zeigt starkes Interesse an der Position.',
    transcript: [
      { speaker: 'agent', text: 'Hallo, hier ist Sophia von Wandel. Spreche ich mit Andi Kufner?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, genau. Guten Tag!', timestamp: '00:04' },
      { speaker: 'agent', text: 'Wunderbar. Ich rufe wegen der Stelle als Servicetechniker für Kaffeeautomaten an. Haben Sie gerade kurz Zeit?', timestamp: '00:07' },
      { speaker: 'candidate', text: 'Ja, natürlich. Ich hatte mich ja beworben.', timestamp: '00:14' },
      { speaker: 'agent', text: 'Super. Können Sie mir kurz etwas über Ihre bisherige Erfahrung erzählen?', timestamp: '00:18' },
      { speaker: 'candidate', text: 'Ich habe eine Ausbildung als Elektrotechniker und war 5 Jahre bei Siemens im Wartungsbereich tätig.', timestamp: '00:25' },
      { speaker: 'agent', text: 'Das klingt sehr gut. Was ist Ihr gewünschtes Gehalt?', timestamp: '00:38' },
      { speaker: 'candidate', text: 'Ich würde mir 2800 Euro netto vorstellen.', timestamp: '00:43' },
      { speaker: 'agent', text: 'Verstanden. Haben Sie einen Führerschein?', timestamp: '00:50' },
      { speaker: 'candidate', text: 'Ja, Klasse B.', timestamp: '00:53' },
      { speaker: 'agent', text: 'Perfekt. Wann könnten Sie frühestens anfangen?', timestamp: '00:56' },
      { speaker: 'candidate', text: 'Ab dem 1. Mai wäre ich verfügbar.', timestamp: '01:01' },
      { speaker: 'agent', text: 'Vielen Dank, Andi. Wir melden uns in Kürze bei Ihnen.', timestamp: '01:07' },
    ],
    audioUrl: null,
    createdAt: '2026-04-11T11:05:00Z',
  },
  {
    id: '3',
    phoneNumber: '+4915141900063',
    email: 'udo.brandt@example.com',
    address: 'Leopoldstr. 56, 80802 München',
    city: 'München',
    firstName: 'Udo',
    lastName: 'Alexander Brandt',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['Low engagement', 'Unclear answers'],
    analysisOutcome: 'interview_completed_partial',
    dateOfBirth: '1979-09-04',
    germanLevel: 'C1',
    training: 'Industriemechaniker',
    salary: null,
    earliestStart: null,
    driversLicense: false,
    licenseClasses: null,
    lastJobs: [],
    jobChangeMotivation: null,
    specialSkills: null,
    additionalPreferences: null,
    status: 'failed',
    employmentStatus: 'employed',
    pipelineStatus: 'talent-pool',
    needForAction: 'low',
    recruiter: 'Itgel',
    touchpoints: 2,
    duration: '1:15',
    lastContactAt: '2026-04-13',
    aiAdoption: 'low',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-12T08:40:00Z',
  },
  {
    id: '4',
    phoneNumber: '+491732392385',
    email: 'andreas.gottschalk@example.com',
    address: 'Schwanthalerstr. 110, 80339 München',
    city: 'München',
    firstName: 'Andreas',
    lastName: 'Gottschalk',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'facebook',
    flags: ['Salary gap'],
    analysisOutcome: 'no_meaningful_interaction',
    dateOfBirth: '1991-07-22',
    germanLevel: 'C1',
    training: 'Mechatronik',
    salary: '3000',
    earliestStart: '2026-06-01',
    driversLicense: true,
    licenseClasses: 'B, BE',
    lastJobs: ['Servicetechniker bei Bosch'],
    jobChangeMotivation: 'Neues Umfeld und interessantere Aufgaben.',
    specialSkills: 'Mechatronik, Hydraulik',
    additionalPreferences: null,
    status: 'done',
    employmentStatus: 'employed',
    pipelineStatus: 'profile-complete',
    needForAction: 'medium',
    recruiter: 'Camilla',
    touchpoints: 4,
    duration: '2:48',
    lastContactAt: '2026-04-16',
    aiAdoption: 'medium',
    terminationReason: 'end_call tool was called.',
    transcriptSummary: 'Andreas Gottschalk hat solide technische Kenntnisse und Erfahrung bei Bosch. Er ist motiviert und flexibel.',
    transcript: [
      { speaker: 'agent', text: 'Guten Tag, ich bin Sophia von Wandel. Spreche ich mit Andreas Gottschalk?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, hallo!', timestamp: '00:05' },
      { speaker: 'agent', text: 'Ich rufe bezüglich der Stelle als Servicetechniker an. Haben Sie Erfahrung in dem Bereich?', timestamp: '00:08' },
      { speaker: 'candidate', text: 'Ja, ich habe 3 Jahre bei Bosch als Servicetechniker gearbeitet.', timestamp: '00:15' },
      { speaker: 'agent', text: 'Was hat Sie an dieser Stelle interessiert?', timestamp: '00:25' },
      { speaker: 'candidate', text: 'Ich suche nach neuen Herausforderungen und einem interessanteren Aufgabengebiet.', timestamp: '00:29' },
    ],
    audioUrl: null,
    createdAt: '2026-04-13T14:20:00Z',
  },
  {
    id: '5',
    phoneNumber: '+4915208512864',
    email: 'giovanni.rossi@example.com',
    address: 'Tegernseer Landstr. 22, 81541 München',
    city: 'München',
    firstName: 'Giovanni',
    lastName: 'Rossi',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'facebook',
    flags: [],
    analysisOutcome: null,
    dateOfBirth: '1992-06-30',
    germanLevel: 'B1',
    training: 'Anlagenmechaniker',
    salary: null,
    earliestStart: null,
    driversLicense: false,
    licenseClasses: null,
    lastJobs: [],
    jobChangeMotivation: null,
    specialSkills: null,
    additionalPreferences: null,
    status: 'in-progress',
    employmentStatus: 'looking-for-job',
    pipelineStatus: 'whatsapp-outreach',
    needForAction: 'high',
    recruiter: 'Tanina',
    touchpoints: 2,
    duration: null,
    lastContactAt: '2026-04-14',
    aiAdoption: 'medium',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-14T16:00:00Z',
  },
  {
    id: '6',
    phoneNumber: '+4915772939762',
    email: 'niclas.gallas@example.com',
    address: 'Sendlinger Tor 3, 80336 München',
    city: 'München',
    firstName: 'Niclas',
    lastName: 'Gallas',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['Voicemail'],
    analysisOutcome: 'voicemail_detected',
    dateOfBirth: '1995-11-03',
    germanLevel: 'B1',
    training: 'Kfz-Mechatronik',
    salary: '2600',
    earliestStart: '2026-05-15',
    driversLicense: true,
    licenseClasses: 'B',
    lastJobs: ['Kfz-Werkstatt Schmidt'],
    jobChangeMotivation: 'Stabilerer Job mit geregelten Arbeitszeiten.',
    specialSkills: 'Fahrzeugtechnik, Diagnose-Software',
    additionalPreferences: null,
    status: 'done',
    employmentStatus: 'unemployed',
    pipelineStatus: 'call',
    needForAction: 'high',
    recruiter: 'Itgel',
    touchpoints: 1,
    duration: '0:32',
    lastContactAt: '2026-04-15',
    aiAdoption: 'low',
    terminationReason: 'voicemail_detection tool was called.',
    transcriptSummary: 'Der Agent hat eine Voicemail hinterlassen. Kein direktes Gespräch zustande gekommen.',
    transcript: [
      { speaker: 'agent', text: 'Hallo, hier ist Sophia von Wandel. Ich rufe wegen Ihrer Bewerbung an. Bitte rufen Sie uns zurück.', timestamp: '00:00' },
    ],
    audioUrl: null,
    createdAt: '2026-04-15T10:15:00Z',
  },
  {
    id: '7',
    phoneNumber: '+4917612345678',
    email: 'klaus.mueller@example.com',
    address: 'Hauptstr. 47, 85221 Dachau',
    city: 'Dachau',
    firstName: 'Klaus',
    lastName: 'Müller',
    jobTitle: 'Lagerlogistiker',
    source: 'facebook',
    flags: [],
    analysisOutcome: 'interview_completed_full',
    dateOfBirth: '1985-05-18',
    germanLevel: 'C2',
    training: 'Lagerlogistik',
    salary: '2400',
    earliestStart: '2026-05-01',
    driversLicense: true,
    licenseClasses: 'B, C1',
    lastJobs: ['DHL Logistik', 'Amazon Fulfillment Center'],
    jobChangeMotivation: 'Näher am Wohnort arbeiten.',
    specialSkills: 'Gabelstapler, SAP Lagerverwaltung',
    additionalPreferences: 'Keine Nachtschicht',
    status: 'done',
    employmentStatus: 'interview-scheduled',
    pipelineStatus: 'matched',
    needForAction: 'medium',
    recruiter: 'Berti',
    touchpoints: 5,
    duration: '5:10',
    lastContactAt: '2026-04-20',
    aiAdoption: 'high',
    terminationReason: 'Call ended by remote party',
    transcriptSummary: 'Klaus Müller hat umfangreiche Erfahrung in der Lagerlogistik und ist sofort verfügbar.',
    transcript: [
      { speaker: 'agent', text: 'Guten Morgen, ich bin Sophia von Wandel. Habe ich Klaus Müller am Apparat?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, guten Morgen.', timestamp: '00:05' },
      { speaker: 'agent', text: 'Sie haben sich auf die Stelle als Lagerlogistiker beworben. Haben Sie einen Staplerschein?', timestamp: '00:08' },
      { speaker: 'candidate', text: 'Ja, den habe ich. Und ich habe auch SAP-Kenntnisse.', timestamp: '00:16' },
    ],
    audioUrl: null,
    createdAt: '2026-04-16T09:30:00Z',
  },
  {
    id: '8',
    phoneNumber: '+4916098765432',
    email: 'sophie.bauer@example.com',
    address: 'Rosenheimer Str. 19, 81669 München',
    city: 'München',
    firstName: 'Sophie',
    lastName: 'Bauer',
    jobTitle: 'Bürokauffrau',
    source: 'facebook',
    flags: ['Language barrier'],
    analysisOutcome: 'consent_declined',
    dateOfBirth: '1993-08-25',
    germanLevel: 'C1',
    training: 'Bürokommunikation',
    salary: '2200',
    earliestStart: '2026-06-01',
    driversLicense: false,
    licenseClasses: null,
    lastJobs: ['Stadtwerke München', 'Kanzlei Fischer & Partner'],
    jobChangeMotivation: 'Weiterkommen und mehr Verantwortung.',
    specialSkills: 'MS Office, Buchhaltung, Kundenkommunikation',
    additionalPreferences: 'Teilzeit möglich',
    status: 'initiated',
    employmentStatus: 'applying',
    pipelineStatus: 'instant-form',
    needForAction: 'medium',
    recruiter: 'Camilla',
    touchpoints: 1,
    duration: null,
    lastContactAt: null,
    aiAdoption: 'medium',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-17T13:45:00Z',
  },
];

export const uniqueJobTitles = [...new Set(mockCandidates.map((c) => c.jobTitle))];
