import type { Candidate, Position } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    phoneNumber: '+4915208526138',
    email: 'marcel.weber@example.com',
    address: 'Augsburger Str. 14, 80337 München',
    city: 'München',
    firstName: 'Marcel',
    lastName: 'Weber',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['No answer'],
    analysisOutcome: 'wrong_person',
    dateOfBirth: '1990-02-18',
    germanLevel: 'B2',
    training: 'Elektroniker für Geräte und Systeme',
    salary: '2900',
    earliestStart: '2026-07-01',
    driversLicense: true,
    licenseClasses: 'B',
    lastJobs: ['Servicetechniker bei Miele', 'Elektroniker bei Bosch', 'Monteur bei Vaillant'],
    jobChangeMotivation: 'Sucht eine wohnortnahe Stelle mit Firmenwagen und mehr Eigenverantwortung im Außendienst.',
    specialSkills: 'Fehlerdiagnose, Hydraulik, Kundenberatung vor Ort',
    additionalPreferences: 'Keine Wochenend- oder Bereitschaftsdienste',
    nationality: 'Deutsch',
    noticePeriod: '4 Wochen zum Monatsende',
    experiences: [
      { role: 'Servicetechniker Hausgeräte', company: 'Miele & Cie. KG', period: '2020 – heute', location: 'München', description: 'Eigenverantwortliche Wartung und Reparatur von Premium-Hausgeräten im Außendienst. Tägliche Tourenplanung für rund 8 Kundeneinsätze sowie Beratung zu Bedienung und Pflege.' },
      { role: 'Elektroniker für Geräte und Systeme', company: 'Robert Bosch GmbH', period: '2015 – 2020', location: 'München', description: 'Inbetriebnahme und Instandsetzung elektronischer Baugruppen, Fehleranalyse anhand von Schaltplänen und Diagnose-Tools in einem 5-köpfigen Serviceteam.' },
      { role: 'Monteur Heizungstechnik', company: 'Vaillant Group', period: '2012 – 2015', location: 'Augsburg', description: 'Montage und Erstinbetriebnahme von Heizsystemen beim Kunden, inklusive Einweisung und Übergabeprotokoll.' },
    ],
    education: [
      { qualification: 'Ausbildung zum Elektroniker für Geräte und Systeme', institution: 'Berufsschule für Elektrotechnik München', period: '2009 – 2012', type: 'ausbildung' },
      { qualification: 'Weiterbildung Kältetechnik (IHK)', institution: 'IHK Akademie München', period: '2018', type: 'weiterbildung' },
    ],
    clientQuestions: [
      { question: 'Wohnen Sie im Großraum München (max. 50 km)?', answer: 'Ja, ich wohne direkt in München-Sendling und bin flexibel in der gesamten Region unterwegs.' },
      { question: 'Haben Sie bereits mit Kaffeevollautomaten oder vergleichbaren Gewerbegeräten gearbeitet?', answer: 'Mit Kaffeevollautomaten noch nicht direkt, aber mit elektromechanisch sehr ähnlichen Hausgeräten bei Miele.' },
      { question: 'Sind Sie bereit, einen Firmenwagen auch privat zu nutzen?', answer: 'Ja, das wäre ideal – ein gepflegter Firmenwagen ist für mich ein klarer Pluspunkt.' },
      { question: 'Wie schnell könnten Sie bei uns anfangen?', answer: 'Mit einer Kündigungsfrist von vier Wochen zum Monatsende, realistisch zum 1. Juli.' },
    ],
    assessment: 'Technisch sehr solider Servicetechniker mit langjähriger Außendiensterfahrung bei Miele und Bosch und Wohnsitz direkt in München. Erfüllt alle Muss-Kriterien (Ausbildung, Führerschein, Sprache, Region); fehlende direkte Kaffeeautomaten-Erfahrung ist aufgrund der übertragbaren Kompetenzen vernachlässigbar. Telefonisch bislang nicht erreicht – ein zweiter Kontaktversuch wird klar empfohlen.',
    status: 'failed',
    employmentStatus: 'looking-for-job',
    pipelineStatus: 'call',
    needForAction: 'high',
    recruiter: 'Tanina',
    touchpoints: 1,
    duration: null,
    lastContactAt: '2026-04-10',
    aiAdoption: 'low',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-10T09:23:00Z',
  },
  {
    id: '2',
    phoneNumber: '+491716437340',
    email: 'andi.kufner@example.com',
    address: 'Marienplatz 8, 80331 München',
    city: 'München',
    firstName: 'Andi',
    lastName: 'Kufner',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: [],
    analysisOutcome: 'interview_completed_full',
    dateOfBirth: '1988-03-14',
    germanLevel: 'B2',
    training: 'Elektrotechnik',
    salary: '2800',
    earliestStart: '2026-05-01',
    driversLicense: true,
    licenseClasses: 'B',
    lastJobs: ['Techniker bei Siemens', 'Wartungsservice GmbH'],
    jobChangeMotivation: 'Bessere Karrieremöglichkeiten und mehr Gehalt.',
    specialSkills: 'Kaffeemaschinen-Reparatur, Elektrik',
    additionalPreferences: 'Homeoffice teilweise möglich',
    nationality: 'Deutsch',
    noticePeriod: '6 Wochen zum Quartalsende',
    experiences: [
      { role: 'Servicetechniker Außendienst', company: 'Siemens AG', period: '2019 – heute', location: 'München', description: 'Wartung und Reparatur industrieller Kaffee- und Heißgetränkeautomaten im Großraum München. Eigenständige Tourenplanung, Ersatzteilmanagement und technische Kundenberatung vor Ort.' },
      { role: 'Techniker Wartung & Instandhaltung', company: 'Wartungsservice GmbH', period: '2014 – 2019', location: 'Rosenheim', description: 'Vorbeugende Wartung elektromechanischer Anlagen, Fehlerdiagnose mit Messtechnik und Dokumentation der Serviceeinsätze.' },
      { role: 'Elektrotechniker', company: 'Elektro Huber GmbH', period: '2011 – 2014', location: 'Rosenheim', description: 'Installation und Inbetriebnahme elektrischer Anlagen, Lesen und Umsetzen technischer Schaltpläne.' },
    ],
    education: [
      { qualification: 'Ausbildung zum Elektrotechniker', institution: 'Staatliche Berufsschule Rosenheim', period: '2008 – 2011', type: 'ausbildung' },
      { qualification: 'Geprüfter Servicetechniker (IHK)', institution: 'IHK Akademie München und Oberbayern', period: '2016', type: 'weiterbildung' },
    ],
    clientQuestions: [
      { question: 'Verfügen Sie über eine abgeschlossene Ausbildung in Elektrotechnik, Mechatronik oder Kfz-Technik?', answer: 'Ja, ich bin gelernter Elektrotechniker und habe zusätzlich die IHK-Weiterbildung zum Servicetechniker.' },
      { question: 'Haben Sie Erfahrung mit Kaffeevollautomaten?', answer: 'Ja, ich betreue bei Siemens seit fünf Jahren genau solche Geräte im Außendienst.' },
      { question: 'Besitzen Sie einen Führerschein der Klasse B?', answer: 'Ja, Klasse B, und ich bin täglich im Außendienst unterwegs.' },
      { question: 'Wann könnten Sie frühestens starten?', answer: 'Ab dem 1. Mai 2026, da meine Kündigungsfrist sechs Wochen zum Quartalsende beträgt.' },
    ],
    assessment: 'Sehr starker Kandidat mit direkt einschlägiger Erfahrung: betreut bei Siemens bereits Kaffee- und Heißgetränkeautomaten im Außendienst und erfüllt sämtliche Muss- und nahezu alle Wunsch-Kriterien. Wohnsitz in München, Führerschein, verhandlungssicheres Deutsch. Gehaltsvorstellung liegt am unteren Rand der Spanne. Klare Empfehlung zur Einladung zum Gespräch.',
    status: 'done',
    employmentStatus: 'applying',
    pipelineStatus: 'matched',
    needForAction: 'low',
    recruiter: 'Berti',
    touchpoints: 3,
    duration: '4:23',
    lastContactAt: '2026-04-14',
    aiAdoption: 'high',
    terminationReason: 'Call ended by remote party',
    transcriptSummary:
      'Der KI-Agent Sophia hat den Kandidaten Andi Kufner erfolgreich interviewt. Er hat relevante Erfahrung in der Elektrotechnik und zeigt starkes Interesse an der Position.',
    transcript: [
      { speaker: 'agent', text: 'Hallo, hier ist Sophia von Wandel. Spreche ich mit Andi Kufner?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, genau. Guten Tag!', timestamp: '00:04' },
      { speaker: 'agent', text: 'Wunderbar. Ich rufe wegen der Stelle als Servicetechniker für Kaffeeautomaten an. Haben Sie gerade kurz Zeit?', timestamp: '00:07' },
      { speaker: 'candidate', text: 'Ja, natürlich. Ich hatte mich ja beworben.', timestamp: '00:14' },
      { speaker: 'agent', text: 'Super. Können Sie mir kurz etwas über Ihre bisherige Erfahrung erzählen?', timestamp: '00:18' },
      { speaker: 'candidate', text: 'Ich habe eine Ausbildung als Elektrotechniker und war 5 Jahre bei Siemens im Wartungsbereich tätig.', timestamp: '00:25' },
      { speaker: 'agent', text: 'Das klingt sehr gut. Was ist Ihr gewünschtes Gehalt?', timestamp: '00:38' },
      { speaker: 'candidate', text: 'Ich würde mir 2800 Euro netto vorstellen.', timestamp: '00:43' },
      { speaker: 'agent', text: 'Verstanden. Haben Sie einen Führerschein?', timestamp: '00:50' },
      { speaker: 'candidate', text: 'Ja, Klasse B.', timestamp: '00:53' },
      { speaker: 'agent', text: 'Perfekt. Wann könnten Sie frühestens anfangen?', timestamp: '00:56' },
      { speaker: 'candidate', text: 'Ab dem 1. Mai wäre ich verfügbar.', timestamp: '01:01' },
      { speaker: 'agent', text: 'Vielen Dank, Andi. Wir melden uns in Kürze bei Ihnen.', timestamp: '01:07' },
    ],
    audioUrl: null,
    createdAt: '2026-04-11T11:05:00Z',
  },
  {
    id: '3',
    phoneNumber: '+4915141900063',
    email: 'udo.brandt@example.com',
    address: 'Leopoldstr. 56, 80802 München',
    city: 'München',
    firstName: 'Udo',
    lastName: 'Alexander Brandt',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['Low engagement', 'Unclear answers'],
    analysisOutcome: 'interview_completed_partial',
    dateOfBirth: '1979-09-04',
    germanLevel: 'C1',
    training: 'Kfz-Mechatroniker',
    salary: '3100',
    earliestStart: '2026-08-01',
    driversLicense: true,
    licenseClasses: 'B, BE',
    lastJobs: ['Kfz-Mechatroniker bei ATU', 'Monteur bei Liebherr', 'Servicekraft bei WMF'],
    jobChangeMotivation: 'Möchte aus der Kfz-Werkstatt in einen planbareren Außendienst mit geregelten Zeiten wechseln.',
    specialSkills: 'Diagnose-Software, Hydraulik, Schweißen',
    additionalPreferences: 'Bevorzugt feste Touren in einer Region',
    nationality: 'Deutsch-österreichisch',
    noticePeriod: '3 Monate zum Quartalsende',
    experiences: [
      { role: 'Kfz-Mechatroniker', company: 'A.T.U Auto-Teile-Unger', period: '2017 – heute', location: 'München', description: 'Diagnose und Reparatur von PKW und leichten Nutzfahrzeugen, Arbeit mit herstellerübergreifender Diagnose-Software und eigenständige Kundenannahme.' },
      { role: 'Servicemonteur', company: 'Liebherr-Hausgeräte GmbH', period: '2011 – 2017', location: 'Ochsenhausen', description: 'Inbetriebnahme und Instandsetzung von Kühl- und Gewerbegeräten beim Kunden, inklusive Kältekreislauf-Arbeiten.' },
      { role: 'Servicekraft Technik', company: 'WMF GmbH', period: '2008 – 2011', location: 'Geislingen', description: 'Unterstützung im technischen Service für Gastronomie-Equipment, erste Berührungspunkte mit professionellen Kaffeemaschinen.' },
    ],
    education: [
      { qualification: 'Ausbildung zum Kfz-Mechatroniker', institution: 'Berufsschule Geislingen an der Steige', period: '2005 – 2008', type: 'ausbildung' },
    ],
    clientQuestions: [
      { question: 'Wohnen Sie im Großraum München (max. 50 km)?', answer: 'Ja, aktuell in München-Moosach.' },
      { question: 'Welche Erfahrung haben Sie mit der Wartung elektronischer Geräte?', answer: 'Hauptsächlich im Kfz-Bereich; mit Kaffeeautomaten nur am Rande bei WMF, das liegt aber länger zurück.' },
      { question: 'Sind Sie mit der Gehaltsspanne von 2.800–3.300 € einverstanden?', answer: 'Ich hatte mir eher 3.100 € aufwärts vorgestellt, da wäre ich auf Ihr Angebot gespannt.' },
      { question: 'Ab wann könnten Sie starten?', answer: 'Das ist noch offen, meine Kündigungsfrist beträgt drei Monate.' },
    ],
    assessment: 'Technisch breit aufgestellter Kandidat mit Kfz- und Servicehintergrund, jedoch nur geringer und länger zurückliegender Bezug zu Kaffeeautomaten. Im Gespräch blieben Verfügbarkeit und Gehaltsvorstellung unklar, die Gehaltserwartung liegt am oberen Ende der Spanne. Grundsätzlich passendes Profil, aber vor einer Weiterempfehlung sollten Motivation und Konditionen in einem zweiten Gespräch geklärt werden.',
    status: 'failed',
    employmentStatus: 'employed',
    pipelineStatus: 'talent-pool',
    needForAction: 'low',
    recruiter: 'Itgel',
    touchpoints: 2,
    duration: '1:15',
    lastContactAt: '2026-04-13',
    aiAdoption: 'low',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-12T08:40:00Z',
  },
  {
    id: '4',
    phoneNumber: '+491732392385',
    email: 'andreas.gottschalk@example.com',
    address: 'Schwanthalerstr. 110, 80339 München',
    city: 'München',
    firstName: 'Andreas',
    lastName: 'Gottschalk',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'facebook',
    flags: ['Salary gap'],
    analysisOutcome: 'no_meaningful_interaction',
    dateOfBirth: '1991-07-22',
    germanLevel: 'C1',
    training: 'Mechatronik',
    salary: '3000',
    earliestStart: '2026-06-01',
    driversLicense: true,
    licenseClasses: 'B, BE',
    lastJobs: ['Servicetechniker bei Bosch'],
    jobChangeMotivation: 'Neues Umfeld und interessantere Aufgaben.',
    specialSkills: 'Mechatronik, Hydraulik',
    additionalPreferences: null,
    status: 'done',
    employmentStatus: 'employed',
    pipelineStatus: 'profile-complete',
    needForAction: 'medium',
    recruiter: 'Camilla',
    touchpoints: 4,
    duration: '2:48',
    lastContactAt: '2026-04-16',
    aiAdoption: 'medium',
    terminationReason: 'end_call tool was called.',
    transcriptSummary: 'Andreas Gottschalk hat solide technische Kenntnisse und Erfahrung bei Bosch. Er ist motiviert und flexibel.',
    transcript: [
      { speaker: 'agent', text: 'Guten Tag, ich bin Sophia von Wandel. Spreche ich mit Andreas Gottschalk?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, hallo!', timestamp: '00:05' },
      { speaker: 'agent', text: 'Ich rufe bezüglich der Stelle als Servicetechniker an. Haben Sie Erfahrung in dem Bereich?', timestamp: '00:08' },
      { speaker: 'candidate', text: 'Ja, ich habe 3 Jahre bei Bosch als Servicetechniker gearbeitet.', timestamp: '00:15' },
      { speaker: 'agent', text: 'Was hat Sie an dieser Stelle interessiert?', timestamp: '00:25' },
      { speaker: 'candidate', text: 'Ich suche nach neuen Herausforderungen und einem interessanteren Aufgabengebiet.', timestamp: '00:29' },
    ],
    audioUrl: null,
    createdAt: '2026-04-13T14:20:00Z',
  },
  {
    id: '5',
    phoneNumber: '+4915208512864',
    email: 'giovanni.rossi@example.com',
    address: 'Tegernseer Landstr. 22, 81541 München',
    city: 'München',
    firstName: 'Giovanni',
    lastName: 'Rossi',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'facebook',
    flags: [],
    analysisOutcome: null,
    dateOfBirth: '1992-06-30',
    germanLevel: 'B1',
    training: 'Anlagenmechaniker',
    salary: null,
    earliestStart: null,
    driversLicense: false,
    licenseClasses: null,
    lastJobs: [],
    jobChangeMotivation: null,
    specialSkills: null,
    additionalPreferences: null,
    status: 'in-progress',
    employmentStatus: 'looking-for-job',
    pipelineStatus: 'whatsapp-outreach',
    needForAction: 'high',
    recruiter: 'Tanina',
    touchpoints: 2,
    duration: null,
    lastContactAt: '2026-04-14',
    aiAdoption: 'medium',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-14T16:00:00Z',
  },
  {
    id: '6',
    phoneNumber: '+4915772939762',
    email: 'niclas.gallas@example.com',
    address: 'Sendlinger Tor 3, 80336 München',
    city: 'München',
    firstName: 'Niclas',
    lastName: 'Gallas',
    jobTitle: 'Servicetechniker für Kaffeeautomaten',
    source: 'instagram',
    flags: ['Voicemail'],
    analysisOutcome: 'voicemail_detected',
    dateOfBirth: '1995-11-03',
    germanLevel: 'B1',
    training: 'Kfz-Mechatronik',
    salary: '2600',
    earliestStart: '2026-05-15',
    driversLicense: true,
    licenseClasses: 'B',
    lastJobs: ['Kfz-Werkstatt Schmidt'],
    jobChangeMotivation: 'Stabilerer Job mit geregelten Arbeitszeiten.',
    specialSkills: 'Fahrzeugtechnik, Diagnose-Software',
    additionalPreferences: null,
    status: 'done',
    employmentStatus: 'unemployed',
    pipelineStatus: 'call',
    needForAction: 'high',
    recruiter: 'Itgel',
    touchpoints: 1,
    duration: '0:32',
    lastContactAt: '2026-04-15',
    aiAdoption: 'low',
    terminationReason: 'voicemail_detection tool was called.',
    transcriptSummary: 'Der Agent hat eine Voicemail hinterlassen. Kein direktes Gespräch zustande gekommen.',
    transcript: [
      { speaker: 'agent', text: 'Hallo, hier ist Sophia von Wandel. Ich rufe wegen Ihrer Bewerbung an. Bitte rufen Sie uns zurück.', timestamp: '00:00' },
    ],
    audioUrl: null,
    createdAt: '2026-04-15T10:15:00Z',
  },
  {
    id: '7',
    phoneNumber: '+4917612345678',
    email: 'klaus.mueller@example.com',
    address: 'Hauptstr. 47, 85221 Dachau',
    city: 'Dachau',
    firstName: 'Klaus',
    lastName: 'Müller',
    jobTitle: 'Lagerlogistiker',
    source: 'facebook',
    flags: [],
    analysisOutcome: 'interview_completed_full',
    dateOfBirth: '1985-05-18',
    germanLevel: 'C2',
    training: 'Lagerlogistik',
    salary: '2400',
    earliestStart: '2026-05-01',
    driversLicense: true,
    licenseClasses: 'B, C1',
    lastJobs: ['DHL Logistik', 'Amazon Fulfillment Center'],
    jobChangeMotivation: 'Näher am Wohnort arbeiten.',
    specialSkills: 'Gabelstapler, SAP Lagerverwaltung',
    additionalPreferences: 'Keine Nachtschicht',
    status: 'done',
    employmentStatus: 'interview-scheduled',
    pipelineStatus: 'matched',
    needForAction: 'medium',
    recruiter: 'Berti',
    touchpoints: 5,
    duration: '5:10',
    lastContactAt: '2026-04-20',
    aiAdoption: 'high',
    terminationReason: 'Call ended by remote party',
    transcriptSummary: 'Klaus Müller hat umfangreiche Erfahrung in der Lagerlogistik und ist sofort verfügbar.',
    transcript: [
      { speaker: 'agent', text: 'Guten Morgen, ich bin Sophia von Wandel. Habe ich Klaus Müller am Apparat?', timestamp: '00:00' },
      { speaker: 'candidate', text: 'Ja, guten Morgen.', timestamp: '00:05' },
      { speaker: 'agent', text: 'Sie haben sich auf die Stelle als Lagerlogistiker beworben. Haben Sie einen Staplerschein?', timestamp: '00:08' },
      { speaker: 'candidate', text: 'Ja, den habe ich. Und ich habe auch SAP-Kenntnisse.', timestamp: '00:16' },
    ],
    audioUrl: null,
    createdAt: '2026-04-16T09:30:00Z',
  },
  {
    id: '8',
    phoneNumber: '+4916098765432',
    email: 'sophie.bauer@example.com',
    address: 'Rosenheimer Str. 19, 81669 München',
    city: 'München',
    firstName: 'Sophie',
    lastName: 'Bauer',
    jobTitle: 'Bürokauffrau',
    source: 'facebook',
    flags: ['Language barrier'],
    analysisOutcome: 'consent_declined',
    dateOfBirth: '1993-08-25',
    germanLevel: 'C1',
    training: 'Bürokommunikation',
    salary: '2200',
    earliestStart: '2026-06-01',
    driversLicense: false,
    licenseClasses: null,
    lastJobs: ['Stadtwerke München', 'Kanzlei Fischer & Partner'],
    jobChangeMotivation: 'Weiterkommen und mehr Verantwortung.',
    specialSkills: 'MS Office, Buchhaltung, Kundenkommunikation',
    additionalPreferences: 'Teilzeit möglich',
    status: 'initiated',
    employmentStatus: 'applying',
    pipelineStatus: 'instant-form',
    needForAction: 'medium',
    recruiter: 'Camilla',
    touchpoints: 1,
    duration: null,
    lastContactAt: null,
    aiAdoption: 'medium',
    terminationReason: null,
    transcriptSummary: null,
    transcript: null,
    audioUrl: null,
    createdAt: '2026-04-17T13:45:00Z',
  },
];

export const uniqueJobTitles = [...new Set(mockCandidates.map((c) => c.jobTitle))];

export const mockPositions: Position[] = [
  {
    id: 'p1',
    title: 'Servicetechniker für Kaffeeautomaten',
    description: `Über uns
Kaffee Partner ist seit über 50 Jahren einer der führenden Anbieter von gewerblichen Kaffeevollautomaten in Deutschland. Mit rund 700 Mitarbeitenden betreuen wir mehr als 70.000 Kunden – vom Handwerksbetrieb bis zum mittelständischen Unternehmen.

Deine Aufgaben
Als Servicetechniker (m/w/d) bist du das Gesicht von Kaffee Partner vor Ort. Du betreust eigenverantwortlich deine Kunden im Großraum München und sorgst dafür, dass unsere Kaffeevollautomaten zuverlässig laufen.
• Wartung, Reparatur und Inbetriebnahme unserer Kaffeevollautomaten beim Kunden
• Eigenständige Tourenplanung mit unserem Service-Tool
• Beratung der Kunden vor Ort zu Bedienung und Produktauswahl
• Enger Austausch mit dem Innendienst in Osnabrück

Dein Profil
Du hast eine technische Ausbildung, gehst gerne auf Menschen zu und arbeitest selbstständig? Dann passt du zu uns.

Wir bieten
• Unbefristete Festanstellung in einem zukunftssicheren Unternehmen
• Voll ausgestatteter Firmenwagen, auch zur privaten Nutzung
• 30 Tage Urlaub und Weihnachtsgeld
• Strukturierte Einarbeitung und kontinuierliche Weiterbildung
• Modernes Werkzeug und hochwertige Arbeitskleidung`,
    employer: 'Kaffee Partner GmbH',
    receivedAt: '2026-04-08',
    candidateCount: 14,
    status: 'open',
    criteria: [
      { id: 'p1-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Abgeschlossene Ausbildung im Bereich Elektrotechnik, Mechatronik oder Kfz-Technik', 'Führerschein Klasse B', 'Deutsch mindestens B2 (Kundenkontakt)', 'Wohnsitz im Großraum München'] },
      { id: 'p1-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['Erste Erfahrung mit Kaffeevollautomaten oder Gewerbegeräten', 'Berufserfahrung im technischen Außendienst', 'Erfahrung in der Kundenberatung vor Ort'] },
      { id: 'p1-c3', title: 'Erfahrung & Werdegang', scoring: 'scale', bullets: ['Mindestens 2 Jahre Berufserfahrung in einem technischen Beruf', 'Erfahrung mit Wartung und Reparatur elektronischer Geräte', 'Idealerweise erste Berührungspunkte mit Außendienst'] },
      { id: 'p1-c4', title: 'Technisches Profil', scoring: 'scale', bullets: ['Grundkenntnisse in Elektrotechnik', 'Sicherer Umgang mit Diagnose-Tools', 'Lesen technischer Schaltpläne'] },
      { id: 'p1-c5', title: 'Sprache & Kommunikation', scoring: 'scale', bullets: ['Verhandlungssicheres Deutsch (B2 oder besser)', 'Souveränes Auftreten beim Kunden', 'Freundliche und lösungsorientierte Kommunikation'] },
      { id: 'p1-c6', title: 'Mobilität & Standort', scoring: 'binary', bullets: ['Wohnort im Großraum München (max. 50 km)', 'Führerschein Klasse B zwingend erforderlich', 'Reisebereitschaft innerhalb der Region'] },
      { id: 'p1-c7', title: 'Persönlichkeit', scoring: 'scale', bullets: ['Eigenverantwortliche, strukturierte Arbeitsweise', 'Hohe Kunden- und Serviceorientierung', 'Hands-on-Mentalität'] },
      { id: 'p1-c8', title: 'Verfügbarkeit', scoring: 'binary', bullets: ['Vollzeit (40 h/Woche)', 'Start: ab sofort oder nach Vereinbarung', 'Kein Bereitschafts- oder Wochenenddienst'] },
      { id: 'p1-c9', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 2.800–3.300 € brutto/Monat', 'Firmenwagen auch zur privaten Nutzung', '30 Tage Urlaub + Weihnachtsgeld', 'Unbefristete Festanstellung'] },
    ],
  },
  {
    id: 'p2',
    title: 'Lagerlogistiker',
    description: 'Wareneingang, Kommissionierung und Versandabwicklung im Schichtbetrieb. Bedienung von Flurförderzeugen und Pflege der Bestandsdaten in SAP.',
    employer: 'DHL Supply Chain',
    receivedAt: '2026-04-12',
    candidateCount: 4,
    status: 'in-progress',
    criteria: [
      { id: 'p2-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Gültiger Staplerschein', 'Bereitschaft zur Schichtarbeit', 'Deutsch mindestens B1'] },
      { id: 'p2-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['SAP-Kenntnisse', 'Erfahrung in der Logistik'] },
      { id: 'p2-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 2.300–2.600 € brutto', 'Start: 01.06.2026', 'Drei-Schicht-System'] },
    ],
  },
  {
    id: 'p3',
    title: 'Bürokauffrau / Bürokaufmann',
    description: 'Allgemeine Verwaltung, Buchhaltung und Kundenkommunikation in Vollzeit. Vorbereitung der Monats- und Jahresabschlüsse in Zusammenarbeit mit dem Steuerberater.',
    employer: 'Kanzlei Fischer & Partner',
    receivedAt: '2026-04-15',
    candidateCount: 2,
    status: 'in-progress',
    criteria: [
      { id: 'p3-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Abgeschlossene kaufmännische Ausbildung', 'Sehr gute MS-Office-Kenntnisse', 'Deutsch C1'] },
      { id: 'p3-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['DATEV-Erfahrung', 'Grundkenntnisse Buchhaltung'] },
      { id: 'p3-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 2.200–2.500 € brutto', 'Vollzeit, 40 h/Woche', 'Teilzeit nach Absprache möglich'] },
    ],
  },
  {
    id: 'p4',
    title: 'Kfz-Mechatroniker',
    description: 'Diagnose und Reparatur von PKW und leichten Nutzfahrzeugen.',
    employer: 'Autohaus Wagner',
    receivedAt: '2026-04-18',
    candidateCount: 3,
    status: 'open',
    criteria: [
      { id: 'p4-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Ausbildung als Kfz-Mechatroniker', 'Führerschein Klasse B', 'Selbstständige Arbeitsweise'] },
      { id: 'p4-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['Erfahrung mit Diagnose-Software', 'Markenkenntnisse VW/Audi'] },
      { id: 'p4-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 2.700–3.100 € brutto', 'Start: nach Absprache'] },
    ],
  },
  {
    id: 'p5',
    title: 'Elektroniker für Betriebstechnik',
    description: 'Installation und Instandhaltung industrieller Anlagen am Standort Ingolstadt. Schwerpunkt auf SPS-gesteuerten Fertigungslinien, Schaltschrankbau und vorbeugender Wartung. Bereitschaftsdienst nach Absprache.',
    employer: 'Siemens AG',
    receivedAt: '2026-04-22',
    candidateCount: 5,
    status: 'complete',
    criteria: [
      { id: 'p5-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Ausbildung als Elektroniker für Betriebstechnik', 'SPS-Grundkenntnisse', 'Bereitschaftsdienst-Bereitschaft'] },
      { id: 'p5-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['Siemens TIA Portal', 'Englischkenntnisse'] },
      { id: 'p5-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 3.200–3.800 € brutto', '30 Tage Urlaub', 'Tarifbindung IG Metall'] },
    ],
  },
  {
    id: 'p6',
    title: 'Pflegefachkraft (m/w/d)',
    description: 'Stationäre Pflege im Drei-Schicht-System, unbefristete Anstellung.',
    employer: 'Caritas Altenheim St. Anna',
    receivedAt: '2026-04-28',
    candidateCount: 1,
    status: 'open',
    criteria: [
      { id: 'p6-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Abgeschlossene Ausbildung als Pflegefachkraft', 'Deutsch mindestens B2', 'Bereitschaft zur Schichtarbeit'] },
      { id: 'p6-c2', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt nach AVR Caritas', 'Unbefristete Festanstellung', 'Zusätzliche Altersvorsorge'] },
    ],
  },
  {
    id: 'p7',
    title: 'Servicetechniker Heizungstechnik',
    description: 'Wartung von Heizungs- und Klimaanlagen bei Privat- und Gewerbekunden. Selbstständige Fehleranalyse, Inbetriebnahme neuer Anlagen sowie Beratung zu Modernisierungs- und Förderoptionen.',
    employer: 'Viessmann Werke',
    receivedAt: '2026-05-03',
    candidateCount: 0,
    status: 'complete',
    criteria: [
      { id: 'p7-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Ausbildung im Bereich SHK oder Heizungsbau', 'Führerschein Klasse B', 'Reisebereitschaft im Großraum'] },
      { id: 'p7-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['Erfahrung mit Wärmepumpen', 'Kenntnisse zu BAFA-Förderungen'] },
      { id: 'p7-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 3.000–3.500 € brutto', 'Firmenwagen zur privaten Nutzung'] },
    ],
  },
  {
    id: 'p8',
    title: 'Produktionshelfer (m/w/d)',
    description: 'Maschinenbedienung und Qualitätskontrolle in der Lebensmittelproduktion.',
    employer: 'Hochland SE',
    receivedAt: '2026-05-10',
    candidateCount: 7,
    status: 'in-progress',
    criteria: [
      { id: 'p8-c1', title: 'Must-Have', scoring: 'binary', bullets: ['Bereitschaft zur Schichtarbeit', 'Körperliche Belastbarkeit', 'Deutsch mindestens A2'] },
      { id: 'p8-c2', title: 'Nice to Have', scoring: 'scale', bullets: ['Erfahrung in der Lebensmittelproduktion', 'Hygienezertifikat'] },
      { id: 'p8-c3', title: 'Konditionen', scoring: 'scale', bullets: ['Gehalt: 2.200–2.400 € brutto', 'Schichtzulagen', 'Kantine vor Ort'] },
    ],
  },
];
